version: '3.1'

services:

  app:
    container_name: gps
    image: gps
    #restart: always
    volumes:
      - "./app/logs:/opt/traccar/logs"
      - "./app/traccar.xml:/opt/traccar/conf/traccar.xml"

    ports:
      - 80:8082
      - 5001-5150:5001-5150
      - 5001-5150:5001-5150/udp
    networks:
      network_app:
        aliases:
          - gps_host

  db:
    container_name: mysql
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    #restart: always
    volumes:
      - "./app/db/data:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gps_db
      MYSQL_USER: traccar
      MYSQL_PASSWORD: firmalinares22
    networks:
      network_app:
        aliases:
          - db_host

#### configuraciones globales
networks:
  network_app:
    name: geo_net #Nombre de la red
    driver: bridge #Tipo de red
    ipam:
      driver: default
